name: bms
volumes:
  bms_postgres:
    name: bms_postgres
networks:
  bms-network:
    driver: bridge

services:
  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - bms-network

  # postgres and pgadmin
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - bms_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_USER=pguser
      - POSTGRES_DB=bms
    networks:
      - bms-network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - bms-network
    ports:
      - "5050:80"
    depends_on:
      - postgres

